site_id: "Paracou"
acquisition_id: "2023-03-09"
out_dir: "./dat/sites/Paracou/INV/2023-03-09/v1"
raw_dir: "./dat/sites/Paracou/INV/2023-03-09/L0"
s3_raw_dir: "johngodlee/GEO-TREES_INV/dat/sites/Paracou/L0"
quad_dim: [50, 50]
opt_s3: false
product_version: "v1"
height_method: "regional"
