site_id: "DanumValley"
acquisition_id: "2018-10-31"
out_dir: "./dat/sites/DanumValley/INV/2018-10-31/v1"
raw_dir: "./dat/sites/DanumValley/INV/2018-10-31/L0"
s3_raw_dir: "johngodlee/GEO-TREES_INV/dat/sites/DanumValley/L0"
quad_dim: [50, 50]
opt_s3: false
product_version: "v1"
height_method: "regional"
