site_id: "Nouragues"
acquisition_id: "2022-12-03"
out_dir: "./dat/sites/Nouragues/INV/2022-12-03/v1"
raw_dir: "./dat/sites/Nouragues/INV/2022-12-03/L0"
s3_raw_dir: "johngodlee/GEO-TREES_INV/dat/sites/Nouragues/L0"
quad_dim: [50, 50]
opt_s3: false
product_version: "v1"
height_method: "regional"
