site_id: "RobsonCreek"
acquisition_id: "2024-10-29"
out_dir: "./dat/sites/RobsonCreek/INV/2024-10-29/v1"
raw_dir: "./dat/sites/RobsonCreek/INV/2024-10-29/L0"
s3_raw_dir: "johngodlee/GEO-TREES_INV/dat/sites/RobsonCreek/L0"
quad_dim: [50, 50]
opt_s3: false
product_version: "v1"
height_method: "regional"
