site_id: "Wanang"
acquisition_id: "2024-10-22"
out_dir: "./dat/sites/Wanang/INV/2024-10-22/v1"
raw_dir: "./dat/sites/Wanang/INV/2024-10-22/L0"
s3_raw_dir: "johngodlee/GEO-TREES_INV/dat/sites/Wanang/L0"
quad_dim: [100, 100]
opt_s3: false
product_version: "v1"
height_method: "regional"
wd_method: "regional"
