site_id: "RobsonCreek"
acquisition_id: "2024-10-29"
out_dir: "./dat/sites/RobsonCreek/2024-10-29"
raw_dir: "./dat/sites/RobsonCreek/2024-10-29/L0"
s3_dir: "johngodlee/GEO-TREES_PDA/dat/sites/RobsonCreek/L0"
quad_dim: [50, 50]
opt_s3: false
