site_id: "PanamaCanal"
acquisition_id: "2023-03-22"
out_dir: "./dat/sites/PanamaCanal/PDA/2023-03-22/v3"
raw_dir: "./dat/sites/PanamaCanal/PDA/2023-03-22/L0"
s3_dir: "johngodlee/GEO-TREES_PDA/dat/sites/PanamaCanal/L0"
quad_dim: [100, 100]
opt_s3: false
product_version: "v3"
height_method: "regional"
wd_method: "regional"
